version: '3.7'

services:
  provider-new:
    build:
      context: '.'
      dockerfile: 'Dockerfile'
  postgresdb:
    image: library/postgres:9.5
    build:
      context: ./db
      dockerfile: Dockerfile
    expose:
      - "5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'postgresdb'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
      PACTBROKER_USER_PASSWORD: 'password'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    restart: 'always'
  pactbroker:
    image: dius/pact-broker
    links:
      - "postgresdb:postgresdb"
    environment:
      PACT_BROKER_DATABASE_PASSWORD: 'password'
      PACT_BROKER_DATABASE_USERNAME: 'pactbrokeruser'
      PACT_BROKER_DATABASE_HOST: 'postgresdb'
      PACT_BROKER_DATABASE_NAME: 'pactbroker'
    ports:
      - "88:80"
    restart: 'always'