version: '3.7'

services:
  provider:
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    ports:
    - "8081:8081"
    depends_on:
      - "postgresdb"

  postgresdb:
    build:
      context: ./db
      dockerfile: Dockerfile
    expose:
      - "5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'postgresdb'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
      PACTBROKER_USER_PASSWORD: 'password'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    restart: 'always'

  pactbroker:
    image: dius/pact-broker
    environment:
      PACT_BROKER_DATABASE_PASSWORD: 'password'
      PACT_BROKER_DATABASE_USERNAME: 'pactbrokeruser'
      PACT_BROKER_DATABASE_HOST: 'postgresdb'
      PACT_BROKER_DATABASE_NAME: 'pactbroker'
    ports:
      - "88:80"
    restart: 'always'

